- name: "create group for ansible user"
  group:
    name: "{{ ansible_playbook_group }}"
    state: present
  tags:
    - ansible-user

- name: "create user processing ansible tasks"
  user:
    comment: User for processing ansible tasks
    name:  "{{ ansible_playbook_user }}"
    group: "{{ ansible_playbook_group }}"
    shell: "/bin/bash"
    append: yes
  tags:
    - ansible-user

- name: "set sudo rights for ansible user"
  template:
    src:  ansible-sudoers.j2
    dest: "/etc/sudoers.d/{{ ansible_playbook_user }}-sudoers"
    owner: root
    group: root
    mode: 0400
  tags:
    - ansible-user

- name: "authorize users to login as ansible user via ssh"
  authorized_key:
    user:  "{{ ansible_playbook_user }}"
    key:   "{{ item.key }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ ansible_users }}"
  when: item.key is defined
  tags:
    - ansible-user
